---
title: "Untitled"
author: "Jan Liekenbrock"
date: '2022-07-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(altair)
library(reticulate)
#reticulate::py_config()
#altair::check_altair()
#altair::install_altair()
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library(tidyverse)
library(countrycode)

library(broom)
library(purrr)


```

```{r}
library(ggthemes)
library(tmap)
library(countrycode)

pal = tableau_color_pal(
  palette = "Tableau 10")(10)

data("World")

World = World%>%
  filter(continent!="Antarctica")

World$wb=countrycode(sourcevar = World$iso_a3,
                        origin = "iso3c",
                         destination = "region")

World = World%>%
  filter(!is.na(wb))

tmap_mode("plot")

tm_shape(World) +
    tm_polygons("wb",palette=pal)

```

```{r}
load("worldbankindicators.RData") 

tmap_mode("view")

currentdata = worldbank_data%>%
  filter(!is.na(Values))%>%
  filter(year == 2020)%>%
  mutate(iso_a3 = 
           countrycode(sourcevar = .$iso2c,
                        origin = "iso2c",
                         destination = "iso3c"))%>%
  filter(!is.na(iso_a3))
  
vars = World%>%left_join(currentdata)

tm_shape(vars) +
    tm_polygons("Values")+
    tm_facets(by = "Indicator",free.scales=TRUE)


```


```{r}
#source("inflationdata.R")
load("inflationdata.RData")

data = data%>%
  mutate(date=as.POSIXct(date))%>%
  mutate(region = countrycode(sourcevar = data$region,
                        origin = "iso3n",
                         destination = "region")
  )%>%
  drop_na()%>%
  group_by(region,`Series Name`,date)%>%
  summarise(value=median(value,na.rm=T))%>%
  drop_na()%>%
  mutate(series = `Series Name`)%>%
  nest(data = -c(region,series))%>% 
  mutate(
    test = map(data, ~ loess(.$value~as.numeric(.$date), span = .5)), # S3 list-col
    tidied = map(test, augment,se.fit=T
    )
  )%>% 
  unnest(c(tidied,data))%>%
  select(-test)%>%
  data.frame()%>%
  mutate(smooth = `.fitted`)

alt$data_transformers$disable_max_rows()


selection = alt$selection_multi(fields=list("region"), bind='legend')

chart <-
  alt$Chart(data)$
  encode(
    x = "date:T",
    y = "smooth:Q",
    color="region:N",
    tooltip='date:T',
    opacity=alt$condition(selection, alt$value(1), alt$value(0.2))
  )$
  mark_line()$
  facet('series',columns=2)$
  interactive()$
    add_selection(
    selection
  )

chart
  
```
